spring.application.name=backend
server.servlet.context-path=/api/v1

# Example for PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.rabzzsdfbqicpiflcltk&password=eLJma9oyLKFPcg1V
spring.datasource.username=postgres.rabzzsdfbqicpiflcltk
spring.datasource.password=eLJma9oyLKFPcg1V
spring.datasource.driver-class-name=org.postgresql.Driver

# If you use Hibernate
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Supabase Database Connection Config
supabase.url=https://rabzzsdfbqicpiflcltk.supabase.co
supabase.key=sb_publishable_6xkb8slnOtPCEiTCOFbH9Q_m1gbIDvr

